name: 05_Checkout Repo and Run code
on: [push]

jobs: 
    checkout-and-display-files-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: |
                pwd
                ls -a
            - name: Checkout Repo
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after and run code
              run: |
                pwd
                ls -a
                python ./sample_code.py
    test-msbuild-validity:
        runs-on: windows-latest
        steps:
            - name: Checkout the Repo again
              run: dir
            - uses: actions/checkout@v3
            - name: list files and run script
              run: | 
                 dir
                 testmsbuild.bat
                 echo "End Code !"
                 
    
                

              
