name: 10_checkout_and_build_unreal
on: [workflow_dispatch]

jobs: 
    checkout-unreal-and-build:
        runs-on: self-hosted
        steps:
            - name: List Files Before
              run: |
                ls
                git config --system core.longpaths true
            - uses: actions/checkout@v4
              with:
                lfs: true
                ref: release
                token: ${{ secrets.PERSONAL_TOKEN }}
                repository: EpicGames/UnrealEngine
                path: Unreal
            - name: list files after and run code
              run: |
                cd Unreal
                ls
                .\Setup.bat
                
