name: Checkout Repo and Run code
on: [push]

jobs: 
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout Repo
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after
              run: ls -a
    depends-on-first:
        runs-on: ubuntu-latest
        needs: [checkout-and-display-files]
        steps:
            - name: run python code
              run: python sample_code.py

            
        