name: Checkout Repo and Run code
on: [push]

jobs: 
    checkout-and-display-files-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: |
                pwd
                ls -a
            - name: Checkout Repo
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after and run code
              run: |
                pwd
                ls -a
                python ./sample_code.py
